// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.EntityFrameworkRepository;

#nullable disable

namespace TodoList.EntityFrameworkRepository.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    [Migration("20251113142703_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("caf9f07b-75b5-4425-8b39-a3880839fa95"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 27, 2, 441, DateTimeKind.Utc).AddTicks(2372),
                            Description = "Got it from Hagrid",
                            Title = "Hogwart's first grader shopping list"
                        },
                        new
                        {
                            Id = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Title = "First grader books"
                        });
                });

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.ToTable("TodoListItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4527444b-24ba-4513-a1c9-0840d0a1a104"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 27, 2, 441, DateTimeKind.Utc).AddTicks(2372),
                            Description = "",
                            IsCompleted = false,
                            Title = "1 Wand",
                            TodoListId = new Guid("caf9f07b-75b5-4425-8b39-a3880839fa95")
                        },
                        new
                        {
                            Id = new Guid("15e7015e-c906-4589-ac9d-1aed41609de9"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 27, 2, 441, DateTimeKind.Utc).AddTicks(2372),
                            Description = "pewter, standard size 2",
                            IsCompleted = false,
                            Title = "1 Cauldron",
                            TodoListId = new Guid("caf9f07b-75b5-4425-8b39-a3880839fa95")
                        },
                        new
                        {
                            Id = new Guid("c97381a8-1611-42fb-980f-30589ef61fb4"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 27, 2, 441, DateTimeKind.Utc).AddTicks(2372),
                            Description = "",
                            IsCompleted = false,
                            Title = "1 telescope",
                            TodoListId = new Guid("caf9f07b-75b5-4425-8b39-a3880839fa95")
                        },
                        new
                        {
                            Id = new Guid("4ef78f57-a4c5-49e9-8bba-e863913d9cb5"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 27, 2, 441, DateTimeKind.Utc).AddTicks(2372),
                            Description = "",
                            IsCompleted = false,
                            Title = "1 set of brass scales",
                            TodoListId = new Guid("caf9f07b-75b5-4425-8b39-a3880839fa95")
                        },
                        new
                        {
                            Id = new Guid("bfc93b39-37a4-4bcd-b5ad-52d026456f19"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 27, 2, 441, DateTimeKind.Utc).AddTicks(2372),
                            Description = "An Owl or a Cat or a Toad",
                            IsCompleted = false,
                            Title = "Students may also bring a pet",
                            TodoListId = new Guid("caf9f07b-75b5-4425-8b39-a3880839fa95")
                        },
                        new
                        {
                            Id = new Guid("c8d87d00-47b3-46bc-a22a-1730d701dac5"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "Grade 1 by Miranda Goshawk",
                            IsCompleted = false,
                            Title = "The Standard Book of Spells",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        },
                        new
                        {
                            Id = new Guid("ad826e1a-e00a-4b11-a6e0-5ab4123d3ad0"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "by Bathilda Bagshot",
                            IsCompleted = false,
                            Title = "A History of Magic",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        },
                        new
                        {
                            Id = new Guid("d27f2c86-c97b-4419-be59-c63bdeb3bff3"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "by Adalbert Waffling",
                            IsCompleted = false,
                            Title = "Magical Theory",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        },
                        new
                        {
                            Id = new Guid("abeaa704-a0de-4b62-855e-dc1e59d88713"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "by Emeric Switch",
                            IsCompleted = false,
                            Title = "A Beginner's Guide to Transfiguration",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        },
                        new
                        {
                            Id = new Guid("e5b38cba-4b9f-4bbc-8709-dd45eee7cd2b"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "by Phyllida Spore",
                            IsCompleted = false,
                            Title = "One Thousand Magical Herbs and Fungi",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        },
                        new
                        {
                            Id = new Guid("5935aece-d1ee-454d-8e8e-7cc9654c42cd"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "by Arsenius Jigger",
                            IsCompleted = false,
                            Title = "Magical Drafts and Potions",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        },
                        new
                        {
                            Id = new Guid("f9b1b7cf-798a-42e8-ad0b-9099214cc1fe"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "by Newt Scamander",
                            IsCompleted = false,
                            Title = "Fantastic Beasts and Where to Find Them",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        },
                        new
                        {
                            Id = new Guid("adf888fe-047c-4723-87eb-8a71edf42b07"),
                            CreatedAt = new DateTime(2025, 11, 11, 14, 32, 2, 444, DateTimeKind.Utc).AddTicks(7159),
                            Description = "by Quentin Trimble",
                            IsCompleted = false,
                            Title = "The Dark Forces: A Guide to Self-Protection",
                            TodoListId = new Guid("97108c8d-542c-41df-9d53-90e26f202ee2")
                        });
                });

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListItemEntity", b =>
                {
                    b.HasOne("TodoList.EntityFrameworkRepository.TodoListEntity", "TodoList")
                        .WithMany("Items")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
