// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.EntityFrameworkRepository;

#nullable disable

namespace EntityFrameworkRepository.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    partial class TodoListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60f2d96b-fdc2-4ac0-a6ba-75b9d28a73e2"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 25, 0, 0, DateTimeKind.Utc),
                            Description = "Got it from Hagrid",
                            Title = "Hogwart's first grader shopping list"
                        },
                        new
                        {
                            Id = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Title = "First grader books"
                        });
                });

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.ToTable("TodoListItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6af576ec-2747-4566-9546-bc2438f4ac3c"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 25, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsCompleted = false,
                            Title = "1 Wand",
                            TodoListId = new Guid("60f2d96b-fdc2-4ac0-a6ba-75b9d28a73e2")
                        },
                        new
                        {
                            Id = new Guid("51ffb482-7312-4330-aa24-975a8114bbb8"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 25, 0, 0, DateTimeKind.Utc),
                            Description = "pewter, standard size 2",
                            IsCompleted = false,
                            Title = "1 Cauldron",
                            TodoListId = new Guid("60f2d96b-fdc2-4ac0-a6ba-75b9d28a73e2")
                        },
                        new
                        {
                            Id = new Guid("fbcad090-3928-470f-bad1-babc87dc14f4"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 25, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsCompleted = false,
                            Title = "1 telescope",
                            TodoListId = new Guid("60f2d96b-fdc2-4ac0-a6ba-75b9d28a73e2")
                        },
                        new
                        {
                            Id = new Guid("9f107bb9-f666-44ff-a711-1a87cf78cfa0"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 25, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsCompleted = true,
                            Title = "1 set of brass scales",
                            TodoListId = new Guid("60f2d96b-fdc2-4ac0-a6ba-75b9d28a73e2")
                        },
                        new
                        {
                            Id = new Guid("d6401c2a-6d89-4e9e-957a-55a93ff0f1ec"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 25, 0, 0, DateTimeKind.Utc),
                            Description = "An Owl or a Cat or a Toad",
                            IsCompleted = false,
                            Title = "Students may also bring a pet",
                            TodoListId = new Guid("60f2d96b-fdc2-4ac0-a6ba-75b9d28a73e2")
                        },
                        new
                        {
                            Id = new Guid("e910a686-58c1-4986-9e12-f860d0774e96"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "Grade 1 by Miranda Goshawk",
                            IsCompleted = true,
                            Title = "The Standard Book of Spells",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        },
                        new
                        {
                            Id = new Guid("d7ede17d-d6bc-4bfa-ad6e-e9ecd7620287"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "by Bathilda Bagshot",
                            IsCompleted = false,
                            Title = "A History of Magic",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        },
                        new
                        {
                            Id = new Guid("a7a73eb5-f57d-4f44-bc3b-7591e402f4b6"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "by Adalbert Waffling",
                            IsCompleted = false,
                            Title = "Magical Theory",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        },
                        new
                        {
                            Id = new Guid("9a8168f7-814f-4a09-9082-e820748e93b3"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "by Emeric Switch",
                            IsCompleted = false,
                            Title = "A Beginner's Guide to Transfiguration",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        },
                        new
                        {
                            Id = new Guid("d7085cd7-a36f-4a76-b778-d9befe0bf332"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "by Phyllida Spore",
                            IsCompleted = true,
                            Title = "One Thousand Magical Herbs and Fungi",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        },
                        new
                        {
                            Id = new Guid("ae11e864-495f-4355-9356-a51873c4df29"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "by Arsenius Jigger",
                            IsCompleted = true,
                            Title = "Magical Drafts and Potions",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        },
                        new
                        {
                            Id = new Guid("aa4773e5-72b4-409a-a1e8-f63ff11821b0"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "by Newt Scamander",
                            IsCompleted = false,
                            Title = "Fantastic Beasts and Where to Find Them",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        },
                        new
                        {
                            Id = new Guid("05d7dd78-25b5-4ead-9da7-b65bde9e247e"),
                            CreatedAt = new DateTime(2025, 11, 12, 10, 28, 0, 0, DateTimeKind.Utc),
                            Description = "by Quentin Trimble",
                            IsCompleted = false,
                            Title = "The Dark Forces: A Guide to Self-Protection",
                            TodoListId = new Guid("d8037978-4e82-489c-bc2e-a1e22e66e1cb")
                        });
                });

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListItemEntity", b =>
                {
                    b.HasOne("TodoList.EntityFrameworkRepository.TodoListEntity", "TodoList")
                        .WithMany("Items")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("TodoList.EntityFrameworkRepository.TodoListEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
